# Generated by Django 3.0.10 on 2021-01-25 10:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Forecast day')),
            ],
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_time', models.DateTimeField(verbose_name='Reading Time')),
                ('location', models.IntegerField(verbose_name='Location number')),
                ('name', models.CharField(max_length=30, verbose_name='Station Name')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('image', models.ImageField(upload_to='images/%Y/%m')),
                ('description', models.TextField(blank=True)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Station Name')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Station Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Station Longitude')),
                ('altitude', models.IntegerField(verbose_name='Station Altitude')),
                ('type', models.CharField(max_length=3, verbose_name='Station Type')),
                ('RFid', models.CharField(blank=True, max_length=2, null=True, verbose_name='Station RFid')),
                ('phone', models.IntegerField(blank=True, null=True, verbose_name='Station Phone')),
            ],
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol_key', models.IntegerField(unique=True, verbose_name='symbol key')),
                ('symbol_image', models.ImageField(blank=True, upload_to='symbols/')),
                ('weather_type', models.CharField(max_length=30, verbose_name='Weather')),
            ],
        ),
        migrations.CreateModel(
            name='Timestep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_time', models.DateTimeField(verbose_name='Time')),
                ('feels_like_temperature', models.IntegerField(verbose_name='Feels like')),
                ('humidity', models.IntegerField(verbose_name='Humidity')),
                ('name', models.IntegerField(verbose_name='Timestep name')),
                ('precipitation', models.IntegerField(verbose_name='%Rain')),
                ('temperature', models.IntegerField(verbose_name='°C')),
                ('uv', models.IntegerField(verbose_name='UV')),
                ('visibility', models.CharField(max_length=2, verbose_name='Visibility')),
                ('weather', models.IntegerField(verbose_name='Symbol')),
                ('wind_direction', models.CharField(max_length=3, verbose_name='Rose')),
                ('wind_gust', models.IntegerField(verbose_name='Gust')),
                ('wind_speed', models.IntegerField(verbose_name='Wind Speed')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesteps', to='weather.Day')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=20, verbose_name='Station status')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Fully operational'), (2, 'Minor service fault'), (3, 'Some readings affected'), (4, 'No readings availabe'), (5, 'Permanently out of service')], default=1)),
                ('summary', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.Station')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_time', models.DateTimeField(verbose_name='Reading Time')),
                ('wind_dir', models.IntegerField(validators=[django.core.validators.MaxValueValidator(360), django.core.validators.MinValueValidator(0)], verbose_name='Wind Direction')),
                ('wind_speed', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Wind Speed')),
                ('wind_gust', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Wind Gust')),
                ('wind_gust_dir', models.IntegerField(validators=[django.core.validators.MaxValueValidator(360), django.core.validators.MinValueValidator(0)], verbose_name='Wind Direction')),
                ('wind_speed_avg2m', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Wind Speed 2m Average')),
                ('wind_dir_avg2m', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(360), django.core.validators.MinValueValidator(0)], verbose_name='Wind Direction 2m Average')),
                ('wind_gust_10m', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Wind Gust 10 minutes')),
                ('wind_gust_dir_10m', models.IntegerField(validators=[django.core.validators.MaxValueValidator(360), django.core.validators.MinValueValidator(0)], verbose_name='Wind Gust Direction 10m')),
                ('humidity', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Relative Humidity')),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Temperature Centigrade')),
                ('rain_1h', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Rain Past Hour')),
                ('rain_today', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Rain Today')),
                ('rain_since_last', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Rain Since Last Reading')),
                ('bar_uncorrected', models.FloatField(verbose_name='Uncorrected pressure')),
                ('bar_corrected', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Barometer (corrected)')),
                ('battery', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Battery')),
                ('light', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Battery')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.Station')),
            ],
        ),
        migrations.AddField(
            model_name='day',
            name='forecast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='weather.Forecast'),
        ),
    ]
