# Generated by Django 3.0.10 on 2020-11-06 11:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='wind_dir_avg2m',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(360), django.core.validators.MinValueValidator(0)], verbose_name='Wind Direction 2m Average'),
        ),
    ]
