# Generated by Django 3.0.10 on 2020-11-26 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_reading_wind_dir_avg2m'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_time', models.DateTimeField(verbose_name='Reading Time')),
                ('location', models.IntegerField(verbose_name='Location number')),
                ('name', models.CharField(max_length=30, verbose_name='Station Name')),
            ],
        ),
        migrations.CreateModel(
            name='Timestep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_time', models.DateTimeField(verbose_name='Timestep')),
                ('feels_like_temperature', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Feels like')),
                ('humidity', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Humidity')),
                ('name', models.IntegerField(verbose_name='Timestep name')),
                ('precipitation', models.IntegerField(verbose_name='Percentage chance of rain')),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Temperature')),
                ('visibility', models.CharField(max_length=2, verbose_name='Visibility')),
                ('weather', models.IntegerField(verbose_name='Weather')),
                ('wind_direction', models.CharField(max_length=3, verbose_name='Wind Direction')),
                ('wind_gust', models.IntegerField(verbose_name='Wind Gust')),
                ('wind_speed', models.IntegerField(verbose_name='Wind Speed')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='times', to='weather.Day')),
            ],
        ),
        migrations.AddField(
            model_name='day',
            name='forecast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='weather.Forecast'),
        ),
    ]
