# Generated by Django 3.0.10 on 2020-11-27 15:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_auto_20201126_1821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forecast',
            old_name='reading_time',
            new_name='forecast_time',
        ),
        migrations.AddField(
            model_name='day',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Forecast day'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timestep',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesteps', to='weather.Day'),
        ),
    ]
