# Generated by Django 3.0.10 on 2020-11-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_auto_20201127_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timestep',
            name='humidity',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Humidity'),
        ),
        migrations.AlterField(
            model_name='timestep',
            name='temperature',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Temperature'),
        ),
    ]
