# Generated by Django 3.0.10 on 2020-11-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0008_auto_20201127_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='timestep',
            name='uv',
            field=models.IntegerField(default=0, verbose_name='UV'),
            preserve_default=False,
        ),
    ]
