# Generated by Django 3.0.10 on 2020-12-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0010_auto_20201203_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='weather_type',
            field=models.CharField(default='NA', max_length=30, verbose_name='Weather'),
            preserve_default=False,
        ),
    ]
