# Generated by Django 3.0.10 on 2021-01-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0011_symbol_weather_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('image', models.ImageField(upload_to='images/%Y/%m')),
                ('description', models.TextField(blank=True)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
