# Generated by Django 3.0.10 on 2021-01-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0012_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='rain_1h',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Rain Past Hour'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='rain_since_last',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Rain Since Last Reading'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='rain_today',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Rain Today'),
        ),
    ]
