# Generated by Django 3.0.10 on 2021-01-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0013_auto_20210105_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='RFid',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Station RFid'),
        ),
        migrations.AlterField(
            model_name='station',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Station Longitude'),
        ),
        migrations.AlterField(
            model_name='station',
            name='phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='Station Phone'),
        ),
    ]
