# Generated by Django 3.0.10 on 2021-01-10 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0014_auto_20210105_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.TextField()),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Fully operational'), (2, 'Minor service fault'), (3, 'Some readings affected'), (4, 'No readings availabe'), (5, 'Permanently out of service')], default=1)),
                ('summary', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.Station')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
