# Generated by Django 3.0.10 on 2021-01-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0015_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='headline',
            field=models.CharField(max_length=20, verbose_name='Station status'),
        ),
    ]
